var _r=Object.getOwnPropertyNames,er=(J,_)=>function(){return _||(0,J[_r(J)[0]])((_={exports:{}}).exports,_),_.exports},ar=er({"hjson-tmp/hjson-common.js"(J,_){"use strict";var B={};function h(r,o){var g,v="",t=0,f=!0,i=0,e;function m(){return e=r.charAt(i),i++,e}for(m(),e==="-"&&(v="-",m());e>="0"&&e<="9";)f&&(e=="0"?t++:f=!1),v+=e,m();if(f&&t--,e===".")for(v+=".";m()&&e>="0"&&e<="9";)v+=e;if(e==="e"||e==="E")for(v+=e,m(),(e==="-"||e==="+")&&(v+=e,m());e>="0"&&e<="9";)v+=e,m();for(;e&&e<=" ";)m();if(o&&(e===","||e==="}"||e==="]"||e==="#"||e==="/"&&(r[i]==="/"||r[i]==="*"))&&(e=0),g=+v,!(e||t||!isFinite(g)))return g}function w(r,o){return Object.defineProperty&&Object.defineProperty(r,"__COMMENTS__",{enumerable:!1,writable:!0}),r.__COMMENTS__=o||{}}function R(r){Object.defineProperty(r,"__COMMENTS__",{value:void 0})}function j(r){return r.__COMMENTS__}function b(r){if(!r)return"";var o=r.split(`
`),g,v,t,f;for(t=0;t<o.length;t++)for(g=o[t],f=g.length,v=0;v<f;v++){var i=g[v];if(i==="#")break;if(i==="/"&&(g[v+1]==="/"||g[v+1]==="*")){g[v+1]==="*"&&(t=o.length);break}else if(i>" "){o[t]="# "+g;break}}return o.join(`
`)}_.exports={EOL:B.EOL||`
`,tryParseNumber:h,createComment:w,removeComment:R,getComment:j,forceComment:b}}}),qr=er({"hjson-tmp/hjson-version.js"(J,_){_.exports="3.2.1"}}),mr=er({"hjson-tmp/hjson-dsf.js"(J,_){"use strict";function B(o,g){if(Object.prototype.toString.apply(o)!=="[object Array]"){if(o)throw new Error("dsf option must contain an array!");return w}else if(o.length===0)return w;var v=[];function t(f){return{}.toString.call(f)==="[object Function]"}return o.forEach(function(f){if(!f.name||!t(f.parse)||!t(f.stringify))throw new Error("extension does not match the DSF interface");v.push(function(){try{if(g=="parse")return f.parse.apply(null,arguments);if(g=="stringify"){var i=f.stringify.apply(null,arguments);if(i!==void 0&&(typeof i!="string"||i.length===0||i[0]==='"'||[].some.call(i,function(e){return R(e)})))throw new Error("value may not be empty, start with a quote or contain a punctuator character except colon: "+i);return i}else throw new Error("Invalid type")}catch(e){throw new Error("DSF-"+f.name+" failed; "+e.message)}})}),h.bind(null,v)}function h(o,g){if(o)for(var v=0;v<o.length;v++){var t=o[v](g);if(t!==void 0)return t}}function w(){}function R(o){return o==="{"||o==="}"||o==="["||o==="]"||o===","}function j(){return{name:"math",parse:function(o){switch(o){case"+inf":case"inf":case"+Inf":case"Inf":return 1/0;case"-inf":case"-Inf":return-1/0;case"nan":case"NaN":return NaN}},stringify:function(o){if(typeof o=="number"){if(1/o===-1/0)return"-0";if(o===1/0)return"Inf";if(o===-1/0)return"-Inf";if(isNaN(o))return"NaN"}}}}j.description="support for Inf/inf, -Inf/-inf, Nan/naN and -0";function b(o){var g=o&&o.out;return{name:"hex",parse:function(v){if(/^0x[0-9A-Fa-f]+$/.test(v))return parseInt(v,16)},stringify:function(v){if(g&&Number.isInteger(v))return"0x"+v.toString(16)}}}b.description="parse hexadecimal numbers prefixed with 0x";function r(){return{name:"date",parse:function(o){if(/^\d{4}-\d{2}-\d{2}$/.test(o)||/^\d{4}-\d{2}-\d{2}T\d{2}\:\d{2}\:\d{2}(?:.\d+)(?:Z|[+-]\d{2}:\d{2})$/.test(o)){var g=Date.parse(o);if(!isNaN(g))return new Date(g)}},stringify:function(o){if(Object.prototype.toString.call(o)==="[object Date]"){var g=o.toISOString();return g.indexOf("T00:00:00.000Z",g.length-14)!==-1?g.substr(0,10):g}}}}r.description="support ISO dates",_.exports={loadDsf:B,std:{math:j,hex:b,date:r}}}}),Fr=er({"hjson-tmp/hjson-parse.js"(J,_){"use strict";_.exports=function(B,h){var w=ar(),R=mr(),j,b,r,o={'"':'"',"'":"'","\\":"\\","/":"/",b:"\b",f:"\f",n:`
`,r:"\r",t:"	"},g,v;function t(){b=0,r=" "}function f(n){return n==="{"||n==="}"||n==="["||n==="]"||n===","||n===":"}function i(n){var c,s=0,a=1;for(c=b-1;c>0&&j[c]!==`
`;c--,s++);for(;c>0;c--)j[c]===`
`&&a++;throw new Error(n+" at line "+a+","+s+" >>>"+j.substr(b-s,20)+" ...")}function e(){return r=j.charAt(b),b++,r}function m(n){return j.charAt(b+n)}function x(n){for(var c="",s=r;e();){if(r===s)return e(),n&&s==="'"&&r==="'"&&c.length===0?(e(),u()):c;if(r==="\\")if(e(),r==="u"){for(var a=0,y=0;y<4;y++){e();var p=r.charCodeAt(0),I;r>="0"&&r<="9"?I=p-48:r>="a"&&r<="f"?I=p-97+10:r>="A"&&r<="F"?I=p-65+10:i("Bad \\u char "+r),a=a*16+I}c+=String.fromCharCode(a)}else if(typeof o[r]=="string")c+=o[r];else break;else r===`
`||r==="\r"?i("Bad string containing newline"):c+=r}i("Bad string")}function u(){for(var n="",c=0,s=0;;){var a=m(-s-5);if(!a||a===`
`)break;s++}function y(){for(var p=s;r&&r<=" "&&r!==`
`&&p-- >0;)e()}for(;r&&r<=" "&&r!==`
`;)e();for(r===`
`&&(e(),y());;){if(!r)i("Bad multiline string");else if(r==="'"){if(c++,e(),c===3)return n.slice(-1)===`
`&&(n=n.slice(0,-1)),n;continue}else for(;c>0;)n+="'",c--;r===`
`?(n+=`
`,e(),y()):(r!=="\r"&&(n+=r),e())}}function O(){if(r==='"'||r==="'")return x(!1);for(var n="",c=b,s=-1;;){if(r===":")return n?s>=0&&s!==n.length&&(b=c+s,i("Found whitespace in your key name (use quotes to include)")):i("Found ':' but no key name (for an empty key name use quotes)"),n;r<=" "?r?s<0&&(s=n.length):i("Found EOF while looking for a key name (check your syntax)"):f(r)?i("Found '"+r+"' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace)"):n+=r,e()}}function d(){for(;r;){for(;r&&r<=" ";)e();if(r==="#"||r==="/"&&m(0)==="/")for(;r&&r!==`
`;)e();else if(r==="/"&&m(0)==="*"){for(e(),e();r&&!(r==="*"&&m(0)==="/");)e();r&&(e(),e())}else break}}function q(){var n=r;for(f(r)&&i("Found a punctuator character '"+r+"' when expecting a quoteless string (check your syntax)");;){e();var c=r==="\r"||r===`
`||r==="";if(c||r===","||r==="}"||r==="]"||r==="#"||r==="/"&&(m(0)==="/"||m(0)==="*")){var s=n[0];switch(s){case"f":if(n.trim()==="false")return!1;break;case"n":if(n.trim()==="null")return null;break;case"t":if(n.trim()==="true")return!0;break;default:if(s==="-"||s>="0"&&s<="9"){var a=w.tryParseNumber(n);if(a!==void 0)return a}}if(c){n=n.trim();var y=v(n);return y!==void 0?y:n}}n+=r}}function C(n,c){var s;for(n--,s=b-2;s>n&&j[s]<=" "&&j[s]!==`
`;s--);j[s]===`
`&&s--,j[s]==="\r"&&s--;var a=j.substr(n,s-n+1);for(s=0;s<a.length;s++)if(a[s]>" "){var y=a.indexOf(`
`);if(y>=0){var p=[a.substr(0,y),a.substr(y+1)];return c&&p[0].trim().length===0&&p.shift(),p}else return[a]}return[]}function $(n){function c(a,y){var p,I,P,l;switch(typeof a){case"string":a.indexOf(y)>=0&&(l=a);break;case"object":if(Object.prototype.toString.apply(a)==="[object Array]")for(p=0,P=a.length;p<P;p++)l=c(a[p],y)||l;else for(I in a)Object.prototype.hasOwnProperty.call(a,I)&&(l=c(a[I],y)||l)}return l}function s(a){var y=c(n,a);return y?"found '"+a+`' in a string value, your mistake could be with:
  > `+y+`
  (unquoted strings contain everything up to the next line!)`:""}return s("}")||s("]")}function F(){var n=[],c,s,a;try{if(g&&(c=w.createComment(n,{a:[]})),e(),s=b,d(),c&&(a=C(s,!0).join(`
`)),r==="]")return e(),c&&(c.e=[a]),n;for(;r;){if(n.push(K()),s=b,d(),r===","&&(e(),s=b,d()),c){var y=C(s);c.a.push([a||"",y[0]||""]),a=y[1]}if(r==="]")return e(),c&&(c.a[c.a.length-1][1]+=a||""),n;d()}i("End of input while parsing an array (missing ']')")}catch(p){throw p.hint=p.hint||$(n),p}}function Y(n){var c="",s={},a,y,p;try{if(g&&(a=w.createComment(s,{c:{},o:[]})),n?y=1:(e(),y=b),d(),a&&(p=C(y,!0).join(`
`)),r==="}"&&!n)return a&&(a.e=[p]),e(),s;for(;r;){if(c=O(),d(),r!==":"&&i("Expected ':' instead of '"+r+"'"),e(),s[c]=K(),y=b,d(),r===","&&(e(),y=b,d()),a){var I=C(y);a.c[c]=[p||"",I[0]||""],p=I[1],a.o.push(c)}if(r==="}"&&!n)return e(),a&&(a.c[c][1]+=p||""),s;d()}if(n)return s;i("End of input while parsing an object (missing '}')")}catch(P){throw P.hint=P.hint||$(s),P}}function K(){switch(d(),r){case"{":return Y();case"[":return F();case"'":case'"':return x(!0);default:return q()}}function M(n,c){var s=b;if(d(),r&&i("Syntax error, found trailing characters"),g){var a=c.join(`
`),y=C(s).join(`
`);if(y||a){var p=w.createComment(n,w.getComment(n));p.r=[a,y]}}return n}function cr(){d();var n=g?C(1):null;switch(r){case"{":return M(Y(),n);case"[":return M(F(),n);default:return M(K(),n)}}function lr(){d();var n=g?C(1):null;switch(r){case"{":return M(Y(),n);case"[":return M(F(),n)}try{return M(Y(!0),n)}catch(c){t();try{return M(K(),n)}catch{throw c}}}if(typeof B!="string")throw new Error("source is not a string");var U=null,D=!0;return h&&typeof h=="object"&&(g=h.keepWsc,U=h.dsf,D=h.legacyRoot!==!1),v=R.loadDsf(U,"parse"),j=B,t(),D?lr():cr()}}}),Sr=er({"hjson-tmp/hjson-stringify.js"(J,_){"use strict";_.exports=function(B,h){var w=ar(),R=mr(),j={obj:["{","}"],arr:["[","]"],key:["",""],qkey:['"','"'],col:[":",""],com:[",",""],str:["",""],qstr:['"','"'],mstr:["'''","'''"],num:["",""],lit:["",""],dsf:["",""],esc:["\\",""],uni:["\\u",""],rem:["",""]},b=w.EOL,r="  ",o=!1,g=!1,v=!1,t=!1,f=0,i=1,e="",m=null,x=!1,u=j;if(h&&typeof h=="object"){h.quotes=h.quotes==="always"?"strings":h.quotes,(h.eol===`
`||h.eol===`\r
`)&&(b=h.eol),o=h.keepWsc,f=h.condense||0,g=h.bracesSameLine,v=h.quotes==="all"||h.quotes==="keys",t=h.quotes==="all"||h.quotes==="strings"||h.separator===!0,t||h.multiline=="off"?i=0:i=h.multiline=="no-tabs"?2:1,e=h.separator===!0?u.com[0]:"",m=h.dsf,x=h.sortProps,typeof h.space=="number"?r=new Array(h.space+1).join(" "):typeof h.space=="string"&&(r=h.space),h.colors===!0&&(u={obj:["\x1B[37m{\x1B[0m","\x1B[37m}\x1B[0m"],arr:["\x1B[37m[\x1B[0m","\x1B[37m]\x1B[0m"],key:["\x1B[33m","\x1B[0m"],qkey:['\x1B[33m"','"\x1B[0m'],col:["\x1B[37m:\x1B[0m",""],com:["\x1B[37m,\x1B[0m",""],str:["\x1B[37;1m","\x1B[0m"],qstr:['\x1B[37;1m"','"\x1B[0m'],mstr:["\x1B[37;1m'''","'''\x1B[0m"],num:["\x1B[36;1m","\x1B[0m"],lit:["\x1B[36m","\x1B[0m"],dsf:["\x1B[37m","\x1B[0m"],esc:["\x1B[31m\\","\x1B[0m"],uni:["\x1B[31m\\u","\x1B[0m"],rem:["\x1B[35m","\x1B[0m"]});var O,d=Object.keys(j);for(O=d.length-1;O>=0;O--){var q=d[O];u[q].push(j[q][0].length,j[q][1].length)}}var C,$="\x7F-\x9F\xAD\u0600-\u0604\u070F\u17B4\u17B5\u200C-\u200F\u2028-\u202F\u2060-\u206F\uFEFF\uFFF0-\uFFFF",F=new RegExp('[\\\\\\"\0-'+$+"]","g"),Y=new RegExp(`^\\s|^"|^'|^#|^\\/\\*|^\\/\\/|^\\{|^\\}|^\\[|^\\]|^:|^,|\\s$|[\0-`+$+"]","g"),K=new RegExp("'''|^[\\s]+$|[\0-"+(i===2?"	":"\b")+"\v\f-"+$+"]","g"),M=new RegExp("^(true|false|null)\\s*((,|\\]|\\}|#|//|/\\*).*)?$"),cr={"\b":"b","	":"t","\n":"n","\f":"f","\r":"r",'"':'"',"\\":"\\"},lr=/[,\{\[\}\]\s:#"']|\/\/|\/\*/,U="",D=0;function n(l,L){return D+=l[0].length+l[1].length-l[2]-l[3],l[0]+L+l[1]}function c(l){return l.replace(F,function(L){var T=cr[L];return typeof T=="string"?n(u.esc,T):n(u.uni,("0000"+L.charCodeAt(0).toString(16)).slice(-4))})}function s(l,L,T,z){return l?(Y.lastIndex=0,M.lastIndex=0,t||T||Y.test(l)||w.tryParseNumber(l,!0)!==void 0||M.test(l)?(F.lastIndex=0,K.lastIndex=0,F.test(l)?!K.test(l)&&!z&&i?a(l,L):n(u.qstr,c(l)):n(u.qstr,l)):n(u.str,l)):n(u.qstr,"")}function a(l,L){var T,z=l.replace(/\r/g,"").split(`
`);if(L+=r,z.length===1)return n(u.mstr,z[0]);var nr=b+L+u.mstr[0];for(T=0;T<z.length;T++)nr+=b,z[T]&&(nr+=L+z[T]);return nr+b+L+u.mstr[1]}function y(l){return l?v||lr.test(l)?(F.lastIndex=0,n(u.qkey,F.test(l)?c(l):l)):n(u.key,l):'""'}function p(l,L,T,z){function nr(k){return k&&k[k[0]==="\r"?1:0]===`
`}function gr(k){return k&&!nr(k)}function tr(k,Br,Er){if(!k)return"";k=w.forceComment(k);var rr,Or=k.length;for(rr=0;rr<Or&&k[rr]<=" ";rr++);return Er&&rr>0&&(k=k.substr(rr)),rr<Or?Br+n(u.rem,k):k}var vr=C(l);if(vr!==void 0)return n(u.dsf,vr);switch(typeof l){case"string":return s(l,U,L,z);case"number":return isFinite(l)?n(u.num,String(l)):n(u.lit,"null");case"boolean":return n(u.lit,String(l));case"object":if(!l)return n(u.lit,"null");var S;o&&(S=w.getComment(l));var Cr=Object.prototype.toString.apply(l)==="[object Array]",yr=U;U+=r;var fr=b+yr,sr=b+U,br=T||g?"":fr,E=[],Z,N=f?[]:null,pr=t,dr=i,xr=e?"":u.com[0],ur=0,W,X,Q,V,or,A,H,G,ir;if(Cr){for(W=0,X=l.length;W<X;W++){if(Z=W<X-1,S?(A=S.a[W]||[],H=gr(A[1]),E.push(tr(A[0],`
`)+sr),N&&(A[0]||A[1]||H)&&(N=null)):E.push(sr),D=0,V=l[W],E.push(p(V,S?H:!1,!0)+(Z?e:"")),N){switch(typeof V){case"string":D=0,t=!0,i=0,N.push(p(V,!1,!0)+(Z?u.com[0]:"")),t=pr,i=dr;break;case"object":if(V){N=null;break}default:N.push(E[E.length-1]+(Z?xr:""));break}Z&&(D+=u.com[0].length-u.com[2]),ur+=D}S&&A[1]&&E.push(tr(A[1],H?" ":`
`,H))}X===0?S&&S.e&&E.push(tr(S.e[0],`
`)+fr):E.push(fr),E.length===0?G=n(u.arr,""):(G=br+n(u.arr,E.join("")),N&&(ir=N.join(" "),ir.length-ur<=f&&(G=n(u.arr,ir))))}else{var jr=S?S.o.slice():[],hr=[];for(Q in l)Object.prototype.hasOwnProperty.call(l,Q)&&jr.indexOf(Q)<0&&hr.push(Q);x&&hr.sort();var wr=jr.concat(hr);for(W=0,X=wr.length;W<X;W++)if(Z=W<X-1,Q=wr[W],S?(A=S.c[Q]||[],H=gr(A[1]),E.push(tr(A[0],`
`)+sr),N&&(A[0]||A[1]||H)&&(N=null)):E.push(sr),D=0,V=l[Q],or=p(V,S&&H),E.push(y(Q)+u.col[0]+(nr(or)?"":" ")+or+(Z?e:"")),S&&A[1]&&E.push(tr(A[1],H?" ":`
`,H)),N){switch(typeof V){case"string":D=0,t=!0,i=0,or=p(V,!1),t=pr,i=dr,N.push(y(Q)+u.col[0]+" "+or+(Z?u.com[0]:""));break;case"object":if(V){N=null;break}default:N.push(E[E.length-1]+(Z?xr:""));break}D+=u.col[0].length-u.col[2],Z&&(D+=u.com[0].length-u.com[2]),ur+=D}X===0?S&&S.e&&E.push(tr(S.e[0],`
`)+fr):E.push(fr),E.length===0?G=n(u.obj,""):(G=br+n(u.obj,E.join("")),N&&(ir=N.join(" "),ir.length-ur<=f&&(G=n(u.obj,ir))))}return U=yr,G}}C=R.loadDsf(m,"stringify");var I="",P=o?P=(w.getComment(B)||{}).r:null;return P&&P[0]&&(I=P[0]+`
`),I+=p(B,null,!0,!0),P&&(I+=P[1]||""),I}}}),Ir=er({"hjson-tmp/hjson-comments.js"(J,_){"use strict";var B=ar();function h(t,f,i){var e;return t&&(e={b:t}),f&&((e=e||{}).a=f),i&&((e=e||{}).x=i),e}function w(t,f){if(!(t===null||typeof t!="object")){var i=B.getComment(t);i&&B.removeComment(t);var e,m,x,u;if(Object.prototype.toString.apply(t)==="[object Array]"){for(u={a:{}},e=0,m=t.length;e<m;e++)b(u.a,e,i.a[e],w(t[e]))&&(x=!0);!x&&i.e&&(u.e=h(i.e[0],i.e[1]),x=!0)}else{u={s:{}};var O,d=Object.keys(t);for(i&&i.o?(O=[],i.o.concat(d).forEach(function(C){Object.prototype.hasOwnProperty.call(t,C)&&O.indexOf(C)<0&&O.push(C)})):O=d,u.o=O,e=0,m=O.length;e<m;e++){var q=O[e];b(u.s,q,i.c[q],w(t[q]))&&(x=!0)}!x&&i.e&&(u.e=h(i.e[0],i.e[1]),x=!0)}return f&&i&&i.r&&(u.r=h(i.r[0],i.r[1])),x?u:void 0}}function R(){var t="";return[].forEach.call(arguments,function(f){f&&f.trim()!==""&&(t&&(t+="; "),t+=f.trim())}),t}function j(t,f){var i=[];if(g(t,f,i,[]),i.length>0){var e=v(f,null,1);e+=`
# Orphaned comments:
`,i.forEach(function(m){e+=("# "+m.path.join("/")+": "+R(m.b,m.a,m.e)).replace(`
`,"\\n ")+`
`}),v(f,e,1)}}function b(t,f,i,e){var m=h(i?i[0]:void 0,i?i[1]:void 0,e);return m&&(t[f]=m),m}function r(t,f){var i=h(f.b,f.a);return i.path=t,i}function o(t,f,i){if(t){var e,m;if(t.a)for(e=0,m=t.a.length;e<m;e++){var x=i.slice().concat([e]),u=t.a[e];u&&(f.push(r(x,u)),o(u.x,f,x))}else t.o&&t.o.forEach(function(O){var d=i.slice().concat([O]),q=t.s[O];q&&(f.push(r(d,q)),o(q.x,f,d))});t.e&&f.push(r(i,t.e))}}function g(t,f,i,e){if(t){if(f===null||typeof f!="object"){o(t,i,e);return}var m,x=B.createComment(f);if(e.length===0&&t.r&&(x.r=[t.r.b,t.r.a]),Object.prototype.toString.apply(f)==="[object Array]"){x.a=[];var u=t.a||{};for(var O in u)if(u.hasOwnProperty(O)){m=parseInt(O);var d=t.a[O];if(d){var q=e.slice().concat([m]);m<f.length?(x.a[m]=[d.b,d.a],g(d.x,f[m],i,q)):(i.push(r(q,d)),o(d.x,i,q))}}m===0&&t.e&&(x.e=[t.e.b,t.e.a])}else x.c={},x.o=[],(t.o||[]).forEach(function(C){var $=e.slice().concat([C]),F=t.s[C];Object.prototype.hasOwnProperty.call(f,C)?(x.o.push(C),F&&(x.c[C]=[F.b,F.a],g(F.x,f[C],i,$))):F&&(i.push(r($,F)),o(F.x,i,$))}),t.e&&(x.e=[t.e.b,t.e.a])}}function v(t,f,i){var e=B.createComment(t,B.getComment(t));return e.r||(e.r=["",""]),(f||f==="")&&(e.r[i]=B.forceComment(f)),e.r[i]||""}_.exports={extract:function(t){return w(t,!0)},merge:j,header:function(t,f){return v(t,f,0)},footer:function(t,f){return v(t,f,1)}}}}),Nr=er({"hjson-tmp/hjson.js"(J,_){var B=ar(),h=qr(),w=Fr(),R=Sr(),j=Ir(),b=mr();_.exports={parse:w,stringify:R,endOfLine:function(){return B.EOL},setEndOfLine:function(r){(r===`
`||r===`\r
`)&&(B.EOL=r)},version:h,rt:{parse:function(r,o){return(o=o||{}).keepWsc=!0,w(r,o)},stringify:function(r,o){return(o=o||{}).keepWsc=!0,R(r,o)}},comments:j,dsf:b.std}}}),kr=Nr();/*!
 * Hjson v3.2.1
 * https://hjson.github.io
 *
 * Copyright 2014-2017 Christian Zangl, MIT license
 * Details and documentation:
 * https://github.com/hjson/hjson-js
 *
 * This code is based on the the JSON version by Douglas Crockford:
 * https://github.com/douglascrockford/JSON-js (json_parse.js, json2.js)
 */export{kr as default};
